"""add columns to table

Revision ID: 679dd8424c11
Revises: 67f5d67aea55
Create Date: 2024-04-13 11:17:35.795410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679dd8424c11'
down_revision = '67f5d67aea55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
